name: CMake MacOS Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  macos-build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
            vcpkgArguments: 'discord-rpc zlib rapidjson openssl'
            vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
            vcpkgGitCommitId: '40616a5e954f7be1077ef37db3fbddbd5dcd1ca6'
            vcpkgTriplet: 'x64-osx'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build-macos

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build-macos
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE='${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake' -DVCPKG_TARGET_TRIPLET=x64-osx

      - name: Build
        working-directory: ${{github.workspace}}/build-macos
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BeamMP-Launcher
          path: ${{github.workspace}}/build-macos/Release/BeamMP-Launcher
